exports.array = [
	'Anniversary',
	'Baby Shower',
	'Bachelor Party',
	'Bachelorette Party',
	'Baptism',
	'Bar/Bat Mitzvah',
	'Birthday',
	'Bridal Shower',
	'Bridesmaid',
	'Cheer up',
	'Christening',
	'Christmas',
	'Communion',
	'Congratulations',
	'Easter',
	'Engagement',
	'Farewell',
	'Get well soon',
	'Good luck',
	'Graduation',
	'Groomsman',
	'Halloween',
	'Housewarming',
	'I miss you',
	'I\'m sorry',
	'Retirement',
	'Thank you',
	'Thinking of you',
	'Wedding'
];

exports.model = [
	{name: 'Anniversary'},
	{name: 'Baby Shower'},
	{name: 'Bachelor Party'},
	{name: 'Bachelorette Party'},
	{name: 'Baptism'},
	{name: 'Bar/Bat Mitzvah'},
	{name: 'Birthday'},
	{name: 'Bridal Shower'},
	{name: 'Bridesmaid'},
	{name: 'Cheer up'},
	{name: 'Christening'},
	{name: 'Christmas'},
	{name: 'Communion'},
	{name: 'Congratulations'},
	{name: 'Easter'},
	{name: 'Engagement'},
	{name: 'Farewell'},
	{name: 'Get well soon'},
	{name: 'Good luck'},
	{name: 'Graduation'},
	{name: 'Groomsman'},
	{name: 'Halloween'},
	{name: 'Housewarming'},
	{name: 'I miss you'},
	{name: 'I\'m sorry'},
	{name: 'Retirement'},
	{name: 'Thank you'},
	{name: 'Thinking of you'},
	{name: 'Wedding'}
];
