exports.array = [
	'Babysitter',
	'Boyfriend',
	'Brother',
	'Client',
	'Co-worker',
	'Dad',
	'Daughter',
	'Employee',
	'Friend',
	'Girlfriend',
	'Granddaughter',
	'Grandfather',
	'Grandmother',
	'Grandson',
	'Husband',
	'Mom',
	'Nephew',
	'Niece',
	'Pet',
	'Sister',
	'Son',
	'Teacher',
	'Wife'
];

exports.model = [
	{name: 'Babysitter'},
	{name: 'Boyfriend'},
	{name: 'Brother'},
	{name: 'Client'},
	{name: 'Co-worker'},
	{name: 'Dad'},
	{name: 'Daughter'},
	{name: 'Employee'},
	{name: 'Friend'},
	{name: 'Girlfriend'},
	{name: 'Granddaughter'},
	{name: 'Grandfather'},
	{name: 'Grandmother'},
	{name: 'Grandson'},
	{name: 'Husband'},
	{name: 'Mom'},
	{name: 'Nephew'},
	{name: 'Niece'},
	{name: 'Pet'},
	{name: 'Sister'},
	{name: 'Son'},
	{name: 'Teacher'},
	{name: 'Wife'}
];

exports.female = [
	{name: 'Babysitter'},
	{name: 'Client'},
	{name: 'Co-worker'},
	{name: 'Daughter'},
	{name: 'Employee'},
	{name: 'Friend'},
	{name: 'Girlfriend'},
	{name: 'Granddaughter'},
	{name: 'Grandmother'},
	{name: 'Mom'},
	{name: 'Niece'},
	{name: 'Pet'},
	{name: 'Sister'},
	{name: 'Teacher'},
	{name: 'Wife'}
];

exports.male = [
	{name: 'Babysitter'},
	{name: 'Boyfriend'},
	{name: 'Brother'},
	{name: 'Client'},
	{name: 'Co-worker'},
	{name: 'Dad'},
	{name: 'Employee'},
	{name: 'Friend'},
	{name: 'Grandfather'},
	{name: 'Grandson'},
	{name: 'Husband'},
	{name: 'Nephew'},
	{name: 'Pet'},
	{name: 'Son'},
	{name: 'Teacher'}
];
